### ISSUE TITLE
Package Status

### ISSUE THREAD

**Issue by Immortalin** [skeeto/devdocs-lookup#2]
Is this still maintained? Any plans to publish to melpa?

**Comment by skeeto** [comment]
I just updated the list of subjects to match devdocs.io, so I guess that
means it's still maintained. :-) I haven't gotten much use out of it, so
I haven't bothered to get it on MELPA, but I'm not against doing so if
it's useful for others.

**Comment by JAremko** [comment]
@skeeto  Would be great to have it at MELPA

**Comment by dustinlacewell** [comment]
Package is broken.
